apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.fullname" . }}-agent
  namespace: {{ .Values.namespace.agent }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent
        {{- include "teamcity.labels" . | nindent 8 }}
    spec:
      containers:
        - name: agent
          # Use the image repository and tag from values.yaml
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: agent-port
              containerPort: 9090
          resources:
            {{- .Values.resources.agent | toYaml | nindent 12 }}
