## A role for TC server to control build agents' pods
## ref: https://www.jetbrains.com/help/teamcity/setting-up-teamcity-for-kubernetes.html
##
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "teamcity.fullname" . }}:manage-agents
  namespace: {{ .Values.namespace.agent }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["list", "get"]