apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: {{ .Values.namespace.server }}
spec:
  containers:
    - name: teamcity-server
      image: busybox
      command:
        - /bin/adduser -D test
        - sleep
        - "3600"
      env:
        {{- range $key, $val := .Values.env.server }}
        - name: "{{ $key }}"
          value: "{{ $val }}"
        {{- end }}
      ports:
        - name: http
          containerPort: 8111
      resources:
        {{- .Values.resources.server | toYaml | nindent 12 }}
      volumeMounts:
        - mountPath: {{ .Values.env.server.TEAMCITY_DATA_PATH }}
          name: data
  securityContext:
    fsGroup: 1000
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: server-data