apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: {{ .Values.namespace.server }}
spec:
  ports:
    - port: 2049
      name: nfs
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{ .Values.namespace.server }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nfs-server
          image: erichough/nfs-server:latest
          # give server pods time to release PVCs before nfs-server is stopped
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 30"]
          ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
          securityContext:
            privileged: true
          env:
            - name: NFS_EXPORT_0
              value: '/exports *(rw,fsid=0,insecure,no_subtree_check)'
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
      volumes:
        - name: nfs-vol
          emptyDir:
            sizeLimit: 500Mi