{{- /*
 * Using Deployment as HAProxy is a stateless service
 */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.fullname" . }}-haproxy
  namespace: {{ .Values.namespace.server }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: haproxy
        {{- include "teamcity.labels" . | nindent 8 }}
    spec:
      containers:
        - name: haproxy
          image: haproxy
          ports:
            - containerPort: 80
            # - containerPort: 443
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: {{ include "teamcity.fullname" . }}-haproxy