# Secret used to pass database credentials to server statefulset
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-auth
  namespace: {{ .Values.namespace.server }}
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
