# TC server service account to control build agents' pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamcity.server.serviceAccountName" . }}
  namespace: {{ .Values.namespace.server }}
