apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity-helm-chart.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
  selector:
    app: {{ include "teamcity-helm-chart.name" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ include "teamcity-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "teamcity-helm-chart.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: teamcity-agent
          # Use the image repository and tag from values.yaml
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.agent }}
            - name: "{{ $key }}"
              value: "{{ $val }}"
            {{- end }}
          ports:
            - name: agent-port
              containerPort: 9090
          resources:
            limits:
              {{- .Values.resources.agent | toYaml | nindent 14 }}
