apiVersion: v1
kind: Service
metadata:
  name: teamcity-agent
  namespace: {{ .Values.namespace.agent }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
  selector:
    app: teamcity-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  namespace: {{ .Values.namespace.agent }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      # restartPolicy: Never # "Never" is not supported in deployments O_o, hope TC will make a good job scalling the pod
      containers:
        - name: teamcity-agent
          # Use the image repository and tag from values.yaml
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.agent }}
            - name: "{{ $key }}"
              value: "{{ $val }}"
            {{- end }}
          ports:
            - name: agent-port
              containerPort: 9090
          resources:
            {{- .Values.resources.agent | toYaml | nindent 12 }}
