apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: {{ .Values.namespace.server }}
spec:
  selector:
    app: haproxy
  ports:
    - name: http
      port: 80
    # - name: https
    #   port: 443
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: {{ .Values.namespace.server }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.9
          ports:
            - containerPort: 80
            # - containerPort: 443
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config