apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgauth
  namespace: {{ .Values.namespace.server }}
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
