apiVersion: v1
kind: ServiceAccount
metadata:
  name: teamcity
  namespace: {{ .Values.namespace.server }}

---

apiVersion: v1
kind: Secret
metadata:
  name: teamcity-secret
  namespace: {{ .Values.namespace.server }}
  annotations:
    kubernetes.io/service-account.name: teamcity
type: kubernetes.io/service-account-token