apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nfs-server.fullname" . }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nfs-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfs-server.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          lifecycle:
            preStop:
              exec:
                # give server pods time to release PVCs before nfs-server is stopped
                command: ["/bin/sh", "-c", "sleep 30"]
          ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
          securityContext:
            privileged: true
          args:
            - /exports
          volumeMounts:
          - name: nfs-data-pvc
            mountPath: /exports
          - name: nfs-server-conf
            mountPath: /etc/exports.d/
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
      - name: nfs-data-pvc
        persistentVolumeClaim:
          claimName: {{ include "nfs-server.fullname" . }}
      - name: nfs-server-conf
        configMap:
          name: {{ include "nfs-server.fullname" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
